### ISSUE TITLE
how to add new post in this project?

### ISSUE THREAD

**Issue by genggeng1104** [look4regev/posey#10]
I have successfully run your project.But i want to know how to add new post? I really need your help. Thank you.

**Comment by look4regev** [comment]
Hi @genggeng1104 , I'm sorry to admit this was an academic playground project with that technology a long time ago and it is not maintained. I don't remember how to add new posts. I hope you were able to figure it out. Sorry for the late reply.
@amirkeren CC

**Comment by amirkeren** [comment]
@genggeng1104 just replace/add the images in the `poses` folder - 
`https://github.com/look4regev/posey/tree/master/public/poses`

**Comment by look4regev** [comment]
Thanks @amirkeren ! 👑 
closing.

**Comment by look4regev** [comment]
@genggeng1104 you're welcome to submit a README.md PR with improved docs to help any future users of the repo.
